### ISSUE TITLE
Maven artefact ID for model syntax project should be more specific.

### ISSUE THREAD

**Issue by carlwilson** [veraPDF/veraPDF-model-syntax#19]
Currently the Maven artefact ID in the [model syntax project POM.xml](https://github.com/veraPDF/veraPDF-model-syntax/blob/master/org.verapdf/pom.xml) is `org.verapdf`.  This is non-specific / plain wrong, I feel it should be something like `model-syntax`.

If this is updated obviously the Xtext dependency in the [POM for the model project](https://github.com/veraPDF/veraPDF-model/blob/master/pom.xml) will need to be updated to match.

**Comment by bdoubrov** [comment]
No real benefit of changing this now.
